package com.xlw.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.ID
     *
     * @mbg.generated Fri Sep 09 16:47:50 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.NAME
     *
     * @mbg.generated Fri Sep 09 16:47:50 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.PASSWORD
     *
     * @mbg.generated Fri Sep 09 16:47:50 CST 2016
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.ID
     *
     * @return the value of s_user.ID
     *
     * @mbg.generated Fri Sep 09 16:47:50 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.ID
     *
     * @param id the value for s_user.ID
     *
     * @mbg.generated Fri Sep 09 16:47:50 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.NAME
     *
     * @return the value of s_user.NAME
     *
     * @mbg.generated Fri Sep 09 16:47:50 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.NAME
     *
     * @param name the value for s_user.NAME
     *
     * @mbg.generated Fri Sep 09 16:47:50 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.PASSWORD
     *
     * @return the value of s_user.PASSWORD
     *
     * @mbg.generated Fri Sep 09 16:47:50 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.PASSWORD
     *
     * @param password the value for s_user.PASSWORD
     *
     * @mbg.generated Fri Sep 09 16:47:50 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }
}